In [11]:
# TODO: Add import statements
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Assign the data to predictor and outcome variables
# TODO: Load the data
train_data = pd.read_csv('data.csv')
train_data

      Var_X     Var_Y
0  -0.33532   6.66854
1   0.02160   3.86398
2  -1.19438   5.16161
3  -0.65046   8.43823
4  -0.28001   5.57201
5   1.93258 -11.13270
6   1.22620  -5.31226
7   0.74727  -4.63725
8   3.32853   3.80650
9   2.87457  -6.06084
10 -1.48662   7.22328
11  0.37629   2.38887
12  1.43918  -7.13415
13  0.24183   2.00412
14 -2.79140   4.29794
15  1.08176  -5.86553
16  2.81555  -5.20711
17  0.54924  -3.52863
18  2.36449 -10.16202
19 -1.01925   5.31123

In [16]:
train_data = pd.read_csv('data.csv')
X = train_data['Var_X'].values.reshape(-1, 1)
y = train_data['Var_Y'].values

# Create polynomial features
# TODO: Create a PolynomialFeatures object, then fit and transform the
# predictor feature
poly_feat = PolynomialFeatures(degree = 4)
X_poly = poly_feat.fit_transform(X)

# Make and fit the polynomial regression model
# TODO: Create a LinearRegression object and fit it to the polynomial predictor
# features
poly_model = LinearRegression(fit_intercept = False).fit(X_poly, y)
poly_model

LinearRegression(copy_X=True, fit_intercept=False, n_jobs=None, normalize=False)